### PR TITLE
implement planar graphs

### PR DESCRIPTION
**Pull request by chadwhitacre**
No edge crossings, and other aesthetic improvements.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Goes towards #61.

**Comment by chadwhitacre** [comment]
For @timothyfcook ... ;-)

screen shot 2015-09-25 at 4 11 12 pm

**Comment by chadwhitacre** [comment]
screen shot 2015-09-25 at 4 31 58 pm
screen shot 2015-09-25 at 4 31 49 pm

**Comment by chadwhitacre** [comment]
Next step is to teach to_svg what to do with the pathways its being given.

**Comment by chadwhitacre** [comment]
screen shot 2015-10-02 at 12 37 16 pm

**Comment by chadwhitacre** [comment]
screen shot 2015-10-02 at 2 10 53 pm

**Comment by dmtroyer** [comment]
!m @whit537

**Comment by chadwhitacre** [comment]
Here's yer screenshot, @timothyfcook. ;-)

screen shot 2015-10-09 at 12 37 23 pm

**Comment by chadwhitacre** [comment]
After lunch I'll look at pruning the search space so the problem is tractable. :-)

**Comment by chadwhitacre** [comment]
https://en.wikipedia.org/wiki/Backtracking

**Comment by chadwhitacre** [comment]
Blech, I'm stuck. What the heck is going on?

**Comment by chadwhitacre** [comment]
```
Called with:             {'art': []}
Solutions:               []
First child:             {'art': [('a', 'deadbeef')]}
Recursing ...           

Called with:             {'art': [('a', 'deadbeef')]}
Solutions:               []
First child:             {'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}
Recursing ...           

Called with:             {'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}
Solutions:               [{'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}]
First child:             None
Cleaning up.            
cleaning up              None
cleaning up              [(0, 0), (1, 1)]
cleaning up              {'art': [<geometry.Segment object at 0x10f309550>]}
cleaned up               None
cleaned up               [(0, 0)]
cleaned up               {'art': []}
Recursed.               

next                     {'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}
next                     [(0, 0)]
next                     2
next                     (0, 0)
next                     (1, 0)
Next sibling:            {'art': [('a', 'deadbeef'), ('b', 'deadbeef')]}
Recursing ...           
```

It's a bug to assign `deadbeef` to both `a` and `b` at the same time.

**Comment by chadwhitacre** [comment]
Where does this bug come from?

**Comment by chadwhitacre** [comment]
Here's [where](https://github.com/saxifrage/caac-map/blob/b263b2cdf39124246f70452d95d6fe00810cf5b5/pathways_solver.py#L155) the assignment actually takes place:

``` python
sibling[P.r2p[resource_id]][-1] = (shape_id, resource_id)
```

**Comment by chadwhitacre** [comment]
We're replacing the last item in the list under whatever pathway id, resulting thereby in the next assignment to be considered.

**Comment by chadwhitacre** [comment]
Given shapes `a` and `b`, and resources `x` and `y`, we end up with this assignment: `[(a,x), (b,y)]` ... and then ...

**Comment by chadwhitacre** [comment]
In this case there _is_ no next assignment to be considered. We should unroll back up to `[(a,x)]` and then   find the next assignment at that level: `[(b,x)]`.

**Comment by chadwhitacre** [comment]
Maybe we need to different clean-up depending on whether we just looked at first or next?

**Comment by chadwhitacre** [comment]
It's something with `indices`, sure feels like ...

**Comment by chadwhitacre** [comment]
What does first do and what do we need to undo?

What does next do and what do we need to undo?

**Comment by chadwhitacre** [comment]
`first` appends to `P.indices` and to `c['foo']`.

**Comment by chadwhitacre** [comment]
Looks like `clean_up` is cleaning up `first` and `reject` (where we append to the list of path segments).

**Comment by chadwhitacre** [comment]
What does `next` do that needs to be undone?

**Comment by chadwhitacre** [comment]
It merely reassigns, it doesn't append.

**Comment by chadwhitacre** [comment]
```
Called with:   {'art': []}
Solutions:     []
First child:   {'art': [('a', 'deadbeef')]}

  Called with:   {'art': [('a', 'deadbeef')]}
  Solutions:     []
  First child:   {'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}

    Called with:   {'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}
    Solutions:     [{'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}]
    First child:   None
    Cleaning up.  
    cleaning up    None
    cleaning up    [(0, 0), (1, 1)]
    cleaning up    {'art': [<geometry.Segment object at 0x10ccc87b8>]}
    cleaned up     None
    cleaned up     [(0, 0)]
    cleaned up     {'art': []}

  next           {'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}
  next           [(0, 0)]
  next           2
  next           (0, 0)
  next           (1, 0)
  Next sibling:  {'art': [('a', 'deadbeef'), ('b', 'deadbeef')]}
```

**Comment by chadwhitacre** [comment]
Why is `next` being called with `{'art': [('a', 'deadbeef'), ('b', 'beeffeed')]}`? Shouldn't it be called with `{'art': [('a', 'deadbeef')]}`?

**Comment by timothyfcook** [comment]
You can do it!

**Comment by chadwhitacre** [comment]
:-)

Got past that bug. On to the next ...

**Comment by chadwhitacre** [comment]
Missing Watson. :disappointed:

**Comment by chadwhitacre** [comment]
``` python
Traceback (most recent call last):
  File "/Users/whit537/workbench/saxifrage/caac-map/test_map.py", line 648, in test_ai_handles_two_pathways  
    solutions = m.assign_ids({'art': ['beef', 'dead'], 'science': ['feed']}, take_first=False)
  File "/Users/whit537/workbench/saxifrage/caac-map/genmap.py", line 364, in assign_ids
    solutions = pathways_solver.solve(self.shapes, pathways)
  File "/Users/whit537/workbench/saxifrage/caac-map/pathways_solver.py", line 109, in solve
    backtrack(problem, root(problem))
  File "/Users/whit537/workbench/saxifrage/caac-map/pathways_solver.py", line 196, in backtrack
    backtrack(P, s)
  File "/Users/whit537/workbench/saxifrage/caac-map/pathways_solver.py", line 196, in backtrack
    backtrack(P, s)
  File "/Users/whit537/workbench/saxifrage/caac-map/pathways_solver.py", line 196, in backtrack
    backtrack(P, s)
  File "/Users/whit537/workbench/saxifrage/caac-map/pathways_solver.py", line 199, in backtrack
    s = next(P, s)
  File "/Users/whit537/workbench/saxifrage/caac-map/pathways_solver.py", line 183, in next
    sibling[P.r2p[resource_id]][-1] = (shape_id, resource_id)
IndexError: list assignment index out of range
```

**Comment by chadwhitacre** [comment]
The science list is empty. That's why the [-1] fails here. It's _supposed_ to be empty at this point.

**Comment by chadwhitacre** [comment]
We shouldn't see `a` assigned twice.

```
Called with:   {'science': [], 'art': []}
Solutions:     0
First child:   {'science': [], 'art': [('a', 'beef')]}

| Called with:   {'science': [], 'art': [('a', 'beef')]}
| Solutions:     0
| First child:   {'science': [], 'art': [('a', 'beef'), ('b', 'dead')]}
|               
| | Called with:   {'science': [], 'art': [('a', 'beef'), ('b', 'dead')]}
| | Solutions:     0
| | First child:   {'science': [('c', 'feed')], 'art': [('a', 'beef'), ('b', 'dead')]}
| |               
| | | Called with:   {'science': [('c', 'feed')], 'art': [('a', 'beef'), ('b', 'dead')]}
| | | Solutions:     1
| | | First child:   None
| | | Cleaning up.  
| |               
| | Prev sibling:  {'science': [], 'art': [('a', 'beef'), ('b', 'dead')]}
| | next           c dead
| | Next sibling:  {'science': [], 'art': [('a', 'beef'), ('c', 'dead')]}
| |               
| | | Called with:   {'science': [], 'art': [('a', 'beef'), ('c', 'dead')]}
| | | Solutions:     1
| | | First child:   {'science': [('a', 'feed')], 'art': [('a', 'beef'), ('c', 'dead')]}
| | |               
| | | | Called with:   {'science': [('a', 'feed')], 'art': [('a', 'beef'), ('c', 'dead')]}
| | | | Solutions:     2
| | | | First child:   None
| | | | Cleaning up.  
| | |               
| | | Prev sibling:  {'science': [], 'art': [('a', 'beef'), ('c', 'dead')]}
| | | next           a feed
```

**Comment by chadwhitacre** [comment]
`{'science': [('a', 'feed')], 'art': [('a', 'beef'), ('c', 'dead')]}`

should be

`{'science': [('b', 'feed')], 'art': [('a', 'beef'), ('c', 'dead')]}`

**Comment by chadwhitacre** [comment]
We shouldn't be appending `(0, 2)`. We should be appending `(1, 2)`.

```
Called with:   {'science': [], 'art': []}
Solutions:     0
first          []
\ appended     (0, 0)
First child:   {'science': [], 'art': [('a', 'beef')]}

| Called with:   {'science': [], 'art': [('a', 'beef')]}
| Solutions:     0
| first          [(0, 0)]
| \ appended     (1, 1)
| First child:   {'science': [], 'art': [('a', 'beef'), ('b', 'dead')]}
|               
| | Called with:   {'science': [], 'art': [('a', 'beef'), ('b', 'dead')]}
| | Solutions:     0
| | first          [(0, 0), (1, 1)]
| | \ appended     (2, 2)
| | First child:   {'science': [('c', 'feed')], 'art': [('a', 'beef'), ('b', 'dead')]}
| |               
| | | Called with:   {'science': [('c', 'feed')], 'art': [('a', 'beef'), ('b', 'dead')]}
| | | Solutions:     1
| | | first          [(0, 0), (1, 1), (2, 2)]
| | | First child:   None
| | | Cleaning up.  
| | | \ popped       (2, 2)
| |               
| | Prev sibling:  {'science': [], 'art': [('a', 'beef'), ('b', 'dead')]}
| | \ set          (2, 1)
| | next           c dead
| | Next sibling:  {'science': [], 'art': [('a', 'beef'), ('c', 'dead')]}
| |               
| | | Called with:   {'science': [], 'art': [('a', 'beef'), ('c', 'dead')]}
| | | Solutions:     1
| | | first          [(0, 0), (2, 1)]
| | | \ appended     (0, 2)
| | | First child:   {'science': [('a', 'feed')], 'art': [('a', 'beef'), ('c', 'dead')]}
| | |               
| | | | Called with:   {'science': [('a', 'feed')], 'art': [('a', 'beef'), ('c', 'dead')]}
| | | | Solutions:     2
| | | | first          [(0, 0), (2, 1), (0, 2)]
| | | | First child:   None
| | | | Cleaning up.  
| | | | \ popped       (0, 2)
| | |               
| | | Prev sibling:  {'science': [], 'art': [('a', 'beef'), ('c', 'dead')]}
| | | \ set          (0, 2)
| | | next           a feed
```

**Comment by chadwhitacre** [comment]
```
 1 \ append (0, 0)          [(0, 0)]
 2 | \ append (1, 1)        [(0, 0), (1, 1)]
 3 | | \ append (2, 2)      [(0, 0), (1, 1), (2, 2)]
 4 | | | \ pop (2, 2)       [(0, 0), (1, 1)]
 5 | | | seek (1, 1)        [(0, 0), (1, 1)]
 6 | | \ set (2, 1)         [(0, 0), (2, 1)]
 7 | | | \ append (0, 2)    [(0, 0), (2, 1), (0, 2)]
 8 | | | | \ pop (0, 2)     [(0, 0), (2, 1)]
 9 | | | | seek (2, 1)      [(0, 0), (2, 1)]
10 | | | \ set (0, 2)       [(0, 0), (0, 2)]
```

**Comment by chadwhitacre** [comment]
`append (0, 2)` on line 7 is wrong. Is `set (2, 1)` on line 6 right?

**Comment by chadwhitacre** [comment]
We need to cycle through the indices somehow. I don't think it's enough to try to compute the next numbers based on `indices[-1]`.

**Comment by chadwhitacre** [comment]
Alright, so these `append`, `pop`, `seek`, and `set` operations need to be implemented using a [`deque`](https://docs.python.org/3/library/collections.html#collections.deque), I think.

**Comment by chadwhitacre** [comment]
`first`, `next`, and `clean_up`

**Comment by chadwhitacre** [comment]
Alright, I hate this.

**Comment by chadwhitacre** [comment]
`next` needs to compute `(1,1)`, `(2,1)`, `(1,2)` and `(2,2)`.

**Comment by chadwhitacre** [comment]
And then `first` needs to compute `(1,2)`, given `[(0,0), (2,1)]`.

**Comment by chadwhitacre** [comment]
I'm staring at this gosh-darn thing and making zero progress. :rage:

**Comment by chadwhitacre** [comment]
WTF?

**Comment by chadwhitacre** [comment]
I mean, what we want is the product of indices:

```
>>> list(it.product(range(3), repeat=2))
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
```

**Comment by chadwhitacre** [comment]
But we have to cram it into this backtracking algorithm.

**Comment by chadwhitacre** [comment]
readimage

**Comment by chadwhitacre** [comment]
http://sahandsaba.com/combinatorial-generation-using-coroutines-in-python.html

**Comment by timothyfcook** [comment]
Coming home tonight! Miss you too Holmes.

**Comment by chadwhitacre** [comment]
http://www.cs.utsa.edu/~wagner/knuth/fasc2a.pdf

**Comment by chadwhitacre** [comment]
My current thinking is that we should be able to know in first() what all the siblings are going to be for this level; first is the first of the siblings.                                                        

Yeah, we should be able to have an iterator for each level that yields the product of ... whatever is available at that level. So at level 0, all indices are available. At level 1, n-1 indices are available. Etc.                                                                                                       

The trick is modifying the pool of available indices at each level.

**Comment by chadwhitacre** [comment]
@timothyfcook I think I'm on to a strategy here, but I'm not going to get it tonight. Would you have time Monday to pair on this? I really want to get this done. :-(

**Comment by chadwhitacre** [comment]
I don't want to wait a whole week to work on this again because a) we're under a deadline, and b) I'll forget everything again. :-(

**Comment by timothyfcook** [comment]
Lots else going on but I would love to pair on Monday! 

Let's do it. Nothing scheduled that day, but will have to do some catchup from being gone.

**Comment by chadwhitacre** [comment]
Thanks.

**Comment by chadwhitacre** [comment]
screen shot 2015-10-19 at 2 25 46 pm

**Comment by timothyfcook** [comment]
woot!

**Comment by chadwhitacre** [comment]
screen shot 2015-10-19 at 10 41 18 pm

screen shot 2015-10-19 at 10 42 19 pm

**Comment by timothyfcook** [comment]
wowzers! What is that??

**Comment by chadwhitacre** [comment]
One way we may be able to reduce our search space will be to apply [this insight](https://github.com/saxifrage/caac-map/blob/77e872a6f3d427a913d70f511f9b29051f5abd01/test_map.py#L733-L734):

>  Reduce the set of actual down to those where w,x,y,z are in order, since the order of the assignment doesn't actually matter to what we're trying to test here.

We don't need to search all `(s,r)` possibilities, we only need to search all `(s,pathway_id)` possibilities.

**Comment by chadwhitacre** [comment]
[Reducing duplication](https://github.com/saxifrage/caac-map/blob/77e872a6f3d427a913d70f511f9b29051f5abd01/pathways_solver.py#L127-L131) may also help.

**Comment by chadwhitacre** [comment]
> wowzers! What is that??

That is a willingness to settle for less-than-fully-complete assignments in order to be able to view _something_ of what is going on. More specifically, it's an [acceptance](https://github.com/saxifrage/caac-map/blob/77e872a6f3d427a913d70f511f9b29051f5abd01/pathways_solver.py#L173-L179) of (linearly) increasingly worse assignments as we near 100,000 nodes covered. I recognize that we need 100% coverage, but I decided to relax that constraint since we were getting down to depth 25 out of 30 fairly quickly and then bouncing around forever down there. What do the 25 assignments so far look like, I wondered.

**Comment by chadwhitacre** [comment]
It also may be the case that integrating shape creation with pathway assignment in a single backtracking algorithm will give us more flexibility: right now we are stuck with a certain fixed set of shapes. What if we could vary the shapes to find better pathways?

**Comment by chadwhitacre** [comment]
Starting off today cleaning up the test suite ...

**Comment by chadwhitacre** [comment]
Going up to 1e6 nodes gets us closer! However, it appears that the edge crossing detection is unreliable:

screen shot 2015-10-23 at 11 13 33 am

Per IRL convo w/ @timothyfcook, I'm going to see about debugging that, and then look at intentionally relaxing the edge crossing constraint in order to achieve 100% assignment so we can land this PR!

**Comment by chadwhitacre** [comment]
I'm working on isolating a test case for edge crossing. I've made a `map.cache` with just `robotics`, which is smallish and reaching 97% within 1e6 nodes, and exhibiting edge crossing.

screen shot 2015-10-23 at 11 24 23 am

**Comment by chadwhitacre** [comment]
This is tricky: I want to interactively debug `reject` when we've got an edge crossing, but a) I can't manually step through 30,000 nodes, and b) it's precisely our test for edge crossing that is failing, so I can't programmatically catch the failure in order to inspect it.

**Comment by chadwhitacre** [comment]
If I can ensure the order in which assignments are made, then I should be able to catch the failure based on the node number we're considering.

**Comment by chadwhitacre** [comment]
Or I could extract a pathway from the failing SVG and run the edge crossing checks against those values.

**Comment by chadwhitacre** [comment]
In coming up with a failing test, I notice that `P.segments` in the acceptable case is only len 4 when I would expect 7. Hmm ...

**Comment by chadwhitacre** [comment]
```
(Pdb) pp c['robots-101']
[('id-tech-java-programming', 'walt-disney-animation-studios-big-hero-6'),
 ('lifelong-kindergarten-group-at-the-mit-media-lab-scratch',
  'christopher-atkeson-build-baymax'),
 ('pittsburgh-first-get-involved', 'carnegie-mellon-university-rumbleblocks-'),
 ('robocup-manuela-veloso---robocup-champion',
  'carnegie-science-center-roboworld'),
 ('super-awesome-sylvia-watercolorbot',
  'carnegie-library-of-pittsburgh-weekly-workshop-at-clp---allegheny'),
 ('walt-disney-animation-studios-big-hero-6', 'assemble-summer-dreamers'),
 ('synn-labs-music-video-with-rube-goldberg-',
  'carnegie-science-center-roboworld-activities'),
 ('wilkinsburg-public-library-unmask---bristle-bot-racers',
  'carnegie-mellon-robotics-academy-expedition-atlantis-')]
(Pdb) pp P.segments['robots-101']
[<Segment 4413370152 (549.5, 148.0) -> (143.0, 115.5)>,
 <Segment 4413366512 (143.0, 115.5) -> (473.5, 327.5)>,
 <Segment 4413370320 (473.5, 327.5) -> (365.5, 464.0)>,
 <Segment 4414410880 (365.5, 464.0) -> (465.5, 465.5)>]
(Pdb)
```

**Comment by chadwhitacre** [comment]
It may not be the case that `segments` should be fully populated by the time we reach an acceptable solution. What is segments when we're rejecting? Is it sufficient for a proper rejection?

**Comment by chadwhitacre** [comment]
```
(Pdb) pp P.segments['robots-101']
[<Segment 4498161960 carnegie-science-center-roboworld(549.5, 148.0) -> carnegie-library-of-pittsburgh-weekly-workshop-at-clp---allegheny(143.0, 115.5)>,
 <Segment 4498165488 carnegie-library-of-pittsburgh-weekly-workshop-at-clp---allegheny(143.0, 115.5) -> assemble-summer-dreamers(473.5, 327.5)>,
 <Segment 4498165040 assemble-summer-dreamers(473.5, 327.5) -> carnegie-science-center-roboworld-activities(365.5, 464.0)>]
(Pdb) pp P.pathways['robots-101']
['walt-disney-animation-studios-big-hero-6',
 'christopher-atkeson-build-baymax',
 'carnegie-mellon-university-rumbleblocks-',
 'carnegie-library-of-pittsburgh-weekly-workshop-at-clp---allegheny',
 'assemble-summer-dreamers',
 'carnegie-mellon-robotics-academy-expedition-atlantis-',
 'carnegie-science-center-roboworld',
 'carnegie-science-center-roboworld-activities']
(Pdb)
```

**Comment by chadwhitacre** [comment]
Shouldn't these be the same?

```
(Pdb) pp [x[1] for x in c['robots-101']]
['walt-disney-animation-studios-big-hero-6',
 'christopher-atkeson-build-baymax',
 'carnegie-mellon-university-rumbleblocks-',
 'carnegie-science-center-roboworld',
 'carnegie-library-of-pittsburgh-weekly-workshop-at-clp---allegheny',
 'assemble-summer-dreamers',
 'carnegie-science-center-roboworld-activities']
(Pdb) pp P.pathways['robots-101']
['walt-disney-animation-studios-big-hero-6',
 'christopher-atkeson-build-baymax',
 'carnegie-mellon-university-rumbleblocks-',
 'carnegie-library-of-pittsburgh-weekly-workshop-at-clp---allegheny',
 'assemble-summer-dreamers',
 'carnegie-mellon-robotics-academy-expedition-atlantis-',
 'carnegie-science-center-roboworld',
 'carnegie-science-center-roboworld-activities']
(Pdb)
```

**Comment by chadwhitacre** [comment]
I mean, I guess not.

**Comment by chadwhitacre** [comment]
But segments should certainly line up with pathways.

**Comment by chadwhitacre** [comment]
Okay! Squished a bug. Pathways seem to in fact be better now but we _are_ still seeing some crossing, as well as some disjoint pathway segments. :-(

screen shot 2015-10-23 at 2 17 48 pm
screen shot 2015-10-23 at 2 17 41 pm
screen shot 2015-10-23 at 2 17 02 pm
screen shot 2015-10-23 at 2 17 10 pm

screen shot 2015-10-23 at 2 18 44 pm
screen shot 2015-10-23 at 2 18 32 pm

**Comment by chadwhitacre** [comment]
Okay! Last thing on this PR is to relax the edge crossing constraint so that we can reach 100% assignment in a reasonable amount of time.

**Comment by chadwhitacre** [comment]
Okay!

**Comment by chadwhitacre** [comment]
screen shot 2015-10-23 at 2 55 46 pm

**Pull request merged**
