### PR TITLE
blocks

### LINKED ISSUE #11: Add multiple grids to a single map.
To replicate Chelsea's complete design.

Do we need to do this from the server?

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #11.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
@timothyfcook I've got the basic logic for generating maps of maps. We are running pretty hard up against the limitations with the current filling algorithm that we have been brute-forcing around via [`meta.py`](https://github.com/saxifrage/caac-map/blob/64ad5a67b36992a576003df96cd094330d777a4a/meta.py): #1 #3 #6.

**Comment by chadwhitacre** [comment]
As I recall we ended up saying last time that we are comfortable randomizing the durations/sizes of the blocks, and that's how we're going to work around the limitations.

**Comment by chadwhitacre** [comment]
It looks like they're all using the same shape:

screen shot 2015-08-14 at 8 32 29 am

**Comment by chadwhitacre** [comment]
That is, all of the smaller shapes are based off of a single one of the pieces of the bigger shape.

**Comment by chadwhitacre** [comment]
Smaller example, faster to test:

```
(env)$ python genmap.py 5 --charset=svg
```

screen shot 2015-08-14 at 8 42 46 am

**Comment by chadwhitacre** [comment]
Squished that one in be7a514:

screen shot 2015-08-14 at 8 47 03 am

**Comment by chadwhitacre** [comment]
Squished in d684158:

screen shot 2015-08-14 at 8 53 25 am

screen shot 2015-08-14 at 8 54 32 am

screen shot 2015-08-14 at 8 54 58 am

**Comment by chadwhitacre** [comment]
Okay! Now how about placing all of the subpieces onto a single SVG?

**Comment by chadwhitacre** [comment]
Boy, I could really go for a lemon bar ...

**Comment by chadwhitacre** [comment]
... or two. :-)

lemon-bars

**Comment by chadwhitacre** [comment]
Blam.

screen shot 2015-08-14 at 10 31 35 am

**Comment by chadwhitacre** [comment]
With the perfect fitting, I'm having a hard time finding a match for the actual data.

```
Iteration: 760207
```

That's for the first of the five shapes.

**Comment by chadwhitacre** [comment]
Actually, I think we need to vary the top-level shape more ...

**Comment by chadwhitacre** [comment]
Hmmm ... still struggling ...

**Comment by chadwhitacre** [comment]
Time for a lemon bar! :-)

**Comment by timothyfcook** [comment]
Hooray! Uber gen map! Thanks for working on it today.

Eat all the lemon bars if necessary!

**Comment by chadwhitacre** [comment]
Sir, yes, sir! :us:

**Comment by chadwhitacre** [comment]
2 left out of 6. :-)

**Comment by chadwhitacre** [comment]
Hypothesis: the randomization at the outer level is conflicting with the randomization at the inner level. By randomizing them independently, we make it less likely that the inner pieces will fit.

**Comment by chadwhitacre** [comment]
Update: two more lemon bars have emerged. Current status: 4 / 8 (50%).

**Comment by chadwhitacre** [comment]
Blech.

**Comment by chadwhitacre** [comment]
Got it. :-)

```
(env)$ python genmap.py output/resources.json -W768 -H1024
```

screen shot 2015-08-15 at 10 49 34 am

**Comment by timothyfcook** [comment]
Hooray! Looking pretty nice sir. What do we have to do to get it up on http://cityasacampus.org/map/ ?

Some of them look a bit skinny/small. The average block sizes for the top-right blocks look much smaller than the left-side blocks.

**Comment by chadwhitacre** [comment]
> What do we have to do to get it up on http://cityasacampus.org/map/?

https://github.com/saxifrage/cityasacampus/issues/175

**Comment by chadwhitacre** [comment]
> Some of them look a bit skinny/small. The average block sizes for the top-right blocks look much smaller than the left-side blocks.

Yup. That's a side-effect of brute-forcing this with monkeys. We can try to improve that if you think it's a priority.

**Comment by timothyfcook** [comment]
C'mon ya monkeys!

Trying to think if there is a way we can get them at least a bit more proportional. The top-grids seems like they're operating on a completely different scale.

**Pull request merged**
